### ISSUE TITLE
Cannot read property 'entryOption' of undefined

### ISSUE THREAD

**Issue by mezhevikin** [Ayctor/laravel-mix-svg-sprite#1]
Hi! I'm getting an error:

```
TypeError: Cannot read property 'entryOption' of undefined
    at SVGSpritemapPlugin.apply (/Users/mezhevikin/Desktop/Projects/examenpdd-vue2/node_modules/svg-spritemap-webpack-plugin/lib/index.js:87:24)
    at Compiler.apply (/Users/mezhevikin/Desktop/Projects/examenpdd-vue2/node_modules/tapable/lib/Tapable.js:375:16)
    at webpack (/Users/mezhevikin/Desktop/Projects/examenpdd-vue2/node_modules/webpack/lib/webpack.js:33:19)
    at processOptions (/Users/mezhevikin/Desktop/Projects/examenpdd-vue2/node_modules/webpack/bin/webpack.js:335:15)
    at yargs.parse (/Users/mezhevikin/Desktop/Projects/examenpdd-vue2/node_modules/webpack/bin/webpack.js:397:2)
    at Object.Yargs.self.parse (/Users/mezhevikin/Desktop/Projects/examenpdd-vue2/node_modules/yargs/yargs.js:533:18)
    at Object.<anonymous> (/Users/mezhevikin/Desktop/Projects/examenpdd-vue2/node_modules/webpack/bin/webpack.js:152:7)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```
Code:
```
require('@ayctor/laravel-mix-svg-sprite');
mix.svgSprite(
    'resources/assets/svg/icons/main/*.svg',
    'resources/assets/svg/sprites/main.svg'
);
```

**Comment by superbiche** [comment]
Had the same issue, fixed in https://github.com/Ayctor/laravel-mix-svg-sprite/pull/2
